[profile.default]
solc = "0.8.24"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 200
verbosity = 2
src = "src"
test = "test"
out = "out"
viaIR = true
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]
ramappings =[
  "src/=src/"
]

[profile.garnet]
eth_rpc_url = "https://rpc.garnetchain.com"

[profile.redstone]
eth_rpc_url = "https://rpc.redstonechain.com"

[profile.sovrun]
eth_rpc_url = "https://sovrun-testchain.rpc.caldera.xyz/http"
# eth_rpc_url = "https://sovrun-testchain.rpc.caldera.xyz/http"

[profile.sovrunl3]
eth_rpc_url = "https://l3.zgv2b.breederdao.io/http"

[profile.hype]
eth_rpc_url = "https://api.hyperliquid-testnet.xyz/evm"

[profile.hypesovrun]
eth_rpc_url = "https://testnet-l2-rpc-hyperliquid.sovrun.org/http"

[profile.hypearbl2]
eth_rpc_url = "https://testnet-chain.sovrun.org/http"

[profile.sepolia]
eth_rpc_url = "https://eth-sepolia.g.alchemy.com/v2/culNXF2K3LsUVn74G0MCmfw8sx2eecf7"

[profile.amoy]
eth_rpc_url = "https://polygon-amoy.g.alchemy.com/v2/culNXF2K3LsUVn74G0MCmfw8sx2eecf7"
